### ISSUE TITLE
Add emergency helpline number [ 1077 ] in the page with respective STD codes.

### ISSUE THREAD

**Issue by officialshaheer** [IEEEKeralaSection/rescuekerala#64] opened 2018-08-16 08:09 UTC

**Comment by anroopak** [comment] 2018-08-16 08:11
Duplicate of  #57

**Comment by naveenpf** [comment] 2018-08-16 11:57
Already ticket is there

**Closed by naveenpf** 2018-08-16 11:57 UTC

**Comment by officialshaheer** [comment] 2018-08-16 20:35
not fixed it yet. :-1:
