### ISSUE TITLE
CSS style issue on district help page

### ISSUE THREAD

**Issue by ninostephen** [IEEEKeralaSection/rescuekerala#67] opened 2018-08-16 08:12 UTC
Guys we have a problem. The text on the district help page for mobile browser....look at the screenshot

![screenshot_2018-08-16-13-37-53](https://user-images.githubusercontent.com/16770117/44196686-3f8af500-a15a-11e8-806f-9da8f3ac65f2.png)

**Comment by tachyons** [comment] 2018-08-16 08:14
Duplicate of #42

**Comment by naveenpf** [comment] 2018-08-16 13:47
Already fixed. If it is still there please report

**Closed by naveenpf** 2018-08-16 13:47 UTC
