### ISSUE TITLE
Pagination in registered request

### ISSUE THREAD

**Issue by MariyaRonald** [IEEEKeralaSection/rescuekerala#604] opened 2018-08-18 15:50 UTC
### Pagination issue 
https://keralarescue.in/requests/?district=ekm&requestee__icontains=&requestee_phone=&location__icontains=
### Your environment

* Chrome browser and its version
* OS Type (iOS/Android/Linux/Windows)

![error](https://user-images.githubusercontent.com/15645432/44300926-70bb1f00-a32c-11e8-9efe-b1d2dca6802b.png)

### Expected behaviour
Scroll in the lower page

### Actual behaviour
Scroll in lower is not available

**Comment by namboodiri** [comment] 2018-08-18 16:10
Pagination is available on the page. #598 is fixing the number of pages shown in pagination view.
If it is something else, could you explain the issue?

**Comment by cvrajeesh** [comment] 2018-08-18 17:47
Please close this as a duplicate of #598

**Comment by bobinson** [comment] 2018-08-18 17:48
duplicate of#598

**Closed by bobinson** 2018-08-18 17:48 UTC
