### ISSUE TITLE
announcement api broken

### ISSUE THREAD

**Issue by tomahawk-pilot** [IEEEKeralaSection/rescuekerala#1060] opened 2019-08-10 18:33 UTC
announcement api is broken. 
https://keralarescue.in/announcements/api
please fix it or move it something generic . like .in/api/announcements

**Comment by neerajmohan96** [comment] 2019-08-10 21:42
I believe the issue is with the url. It seems  /announcements/api is clashing  with /announcements/`<string:filter>` in mainapp/urls.py

**Comment by bobinson** [comment] 2019-08-11 02:33
fixed via https://github.com/neerajmohan96/rescuekerala/pull/1

**Comment by bobinson** [comment] 2019-08-11 02:47
closed by mistake.

**Comment by vigneshhari** [comment] 2019-08-11 07:20
https://keralarescue.in/api/announcements/api  Its still there working without any issues

**Closed by vigneshhari** 2019-08-11 07:20 UTC
Labels: important, urgent
