### ISSUE TITLE
Server Error (500)

### ISSUE THREAD

**Issue by sreejithc321** [IEEEKeralaSection/rescuekerala#365] opened 2018-08-17 12:47 UTC
### Subject of the issue
https://keralarescue.in/request/ is down now?

6:17 PM
Friday, 17 August 2018 (IST)

**Comment by namboodiri** [comment] 2018-08-17 12:51
It has been fixed now.

**Closed** 2018-08-17 12:54 UTC

**Comment by realslimshanky** [comment] 2018-08-17 12:57
@sreejithc321 please close the issue is you are not having any more trouble.
