### ISSUE TITLE
QR code to display in https://keralarescue.in/reg_contrib/

### ISSUE THREAD

**Issue by nithin19888** [IEEEKeralaSection/rescuekerala#402] opened 2018-08-17 16:05 UTC
### Subject of the issue
CM relief fund redirection (https://donation.cmdrf.kerala.gov.in/) loading too slow and hence recommended to display the QR codes directly in this page,  https://keralarescue.in/reg_contrib/ for easy transfer

**Comment by salmanulfarzy** [comment] 2018-08-17 16:38
Duplicate of #25  
Duplicate of #36 
Duplicate of #52 
Duplicate of #90  
Duplicate of #141
Duplicate of #350

**Comment by gauravsaini** [comment] 2018-08-17 16:40
SOUTH INDIAN BANK PAYMENT GATEWAY SERVICES 
Internet Banking - 50 banks supported
Domestic Credit and Debit Cards supported

payment charges: Nil ACCOUNT DETAILS
A/c Number : 0721053000002584 
A/c Name: Chief Minister’s Distress Relief Fund
Branch : Corporate Branch, Thiruvananthapuram
IFSC : SIBL0000721

https://donation.cmdrf.kerala.gov.in//assets/images/upi-southindianbank.png


FEDERAL BANK PAYMENT GATEWAY SERVICES 
Internet Banking - 53 banks supported
Domestic Credit and Debit Cards supported
UPI payment supported

payment charges: Nil ACCOUNT DETAILS 
A/c Number : 10210100412397
A/c Name: Chief Minister’s Distress Relief Fund
Branch: Thiruvananthapuram/Palayam
IFSC : FDRL0001021

(https://donation.cmdrf.kerala.gov.in//assets/images/upi-federalbank.png)

AIRTEL PAYMENTS BANK PAYMENT GATEWAY SERVICES 
Airtel Payments bank
Airtel Wallet

payment charges: Nil

(https://donation.cmdrf.kerala.gov.in//assets/images/upi-airtel.png)

STATE BANK OF INDIA PAYMENT GATEWAY SERVICES 
Internet Banking - 40 banks supported
Domestic Credit and Debit Cards supported

payment charges: Nil
Payments can also be given through Kerala Government Portal

ACCOUNT DETAILS 
A/c Number : 67319948232
A/c Name: Chief Minister’s Distress Relief Fund
Branch: City Branch, Thiruvananthapuram
IFSC : SBIN0070028

(https://donation.cmdrf.kerala.gov.in//assets/images/upi-sbi.png)

PAYTM SMART URL SERVICE 
m.p-y.tm/Kerala-CMDRF

payment charges: Nil

(https://donation.cmdrf.kerala.gov.in//assets/images/upi-paytm.png)

**Comment by anithark21** [comment] 2018-08-17 17:42
![qrcode](https://user-images.githubusercontent.com/37607672/44280639-f7132a80-a272-11e8-82bc-6ca62210df45.png)

**Comment by malgamves** [comment] 2018-08-17 18:54
Anyone working on this?

**Comment by aravindharinair** [comment] 2018-08-17 19:40
I'm not experienced in Django but I'm comfortable with HTML/CSS. I'll see what I can do.

**Comment by arjunkomath** [comment] 2018-08-17 20:03
Working on it.

**Comment by aravindharinair** [comment] 2018-08-17 20:12
@arjunkomath , I'm also working on it.
I think I have it but I don't know how to test it...

**Comment by arjunkomath** [comment] 2018-08-17 20:14
Follow the instruction shows [here](https://github.com/IEEEKeralaSection/rescuekerala) to setup and test locally.

**Comment by aravindharinair** [comment] 2018-08-17 20:16
Ok. Thank you. I'll test it out and let you know.

**Comment by aravindharinair** [comment] 2018-08-17 20:42
I was late, apparently. :/
Anyway, this is how it looks. 
Is it fine?
@colonelrascals has already submitted a PR, so I'm not repeating it...

![qr added](https://user-images.githubusercontent.com/19900170/44287872-123e6400-a28c-11e8-84d9-50f3a225aaa3.png)

**Comment by arjunkomath** [comment] 2018-08-17 21:06
@aravindharinair I've added the full info:

![donations-info](https://user-images.githubusercontent.com/2555067/44288856-dc48b200-a282-11e8-860a-56155d87aea3.png)

**Closed** 2018-08-18 22:15 UTC
Labels: good first issue, help wanted
