### ISSUE TITLE
Create direct donation payment to CMDRF account in home page with paypal integration.

### ISSUE THREAD

**Issue by zubairkumbla** [IEEEKeralaSection/rescuekerala#679] opened 2018-08-19 09:43 UTC
### Subject of the issue
Describe your issue here.

### Your environment
* version of your python
* which browser and its version
* OS Type (iOS/Android/Linux/Windows)

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo as a GIF, if possible.

### Expected behaviour
Tell us what and how exactly is it supposed to  happen

### Actual behaviour
Tell us what happens instead or what went wrong

[](https://developer.paypal.com/docs/integration/web/#availability)

**Comment by riginoommen** [comment] 2018-08-19 09:56
Thanks for filing the Issue 

But seems to be duplicate of #509

**Comment by riginoommen** [comment] 2018-08-19 09:57
Please forward the communication at #509

**Closed** 2018-08-19 09:58 UTC
Labels: duplicate

**Comment by aravindharinair** [comment] 2018-08-19 10:00
Solution proposed and awaiting merge at PR #614

**Comment by bobinson** [comment] 2018-08-22 09:34
#509
