### ISSUE TITLE
scroll issue in  request details page

### ISSUE THREAD

**Issue by shamonshan** [IEEEKeralaSection/rescuekerala#132] opened 2018-08-16 12:35 UTC
Steps to reproduce
----------------------------

1)Open the page https://keralarescue.in/requests/.

2) Select a district and click the submit button.

Actual behavior
---------------------
Listed data in a table but the horizontal scroll is not visible

Expected
-------------------
Should list the data with proper scroll

**Comment by gauthams09** [comment] 2018-08-16 12:40
This might have come up after fixing #121

**Comment by bobinson** [comment] 2018-08-16 12:43
Few additional thoughts:


![image](https://user-images.githubusercontent.com/18070249/44209086-f9488c80-a17f-11e8-9fa4-b65b2aac4aa4.png)

**Comment by naveenpf** [comment] 2018-08-16 13:32
Is this issue still seen ?

**Comment by gauthams09** [comment] 2018-08-16 13:58
yep

**Comment by abhaga** [comment] 2018-08-16 14:17
This is being caused by very long URLs in the "Summary of request" column. A quick fix is to set `overflow-x: visible` on the top `div.table-responsive`.

**Comment by kracekumar** [comment] 2018-08-16 14:56
this is how @abhaga changes look

![Uploading original.png…](In site
![Uploading modified.png…](After CSS changes)
)

**Comment by bobinson** [comment] 2018-08-16 15:00
@kracekumar - what about smaller screens ? perhaps you can test with responsiveness.

**Comment by kracekumar** [comment] 2018-08-16 15:13
With my limited understanding of responsiveness, it seems to work @bobinson 

Original

![512_original](https://user-images.githubusercontent.com/311929/44217367-ed1afa00-a194-11e8-8ffc-53c12aab1165.png)
 to work.

Modified

![512_modified](https://user-images.githubusercontent.com/311929/44217393-f60bcb80-a194-11e8-84fb-32fea52760d6.png)

**Comment by naveenpf** [comment] 2018-08-16 15:35
Who is working this issue now ?

**Comment by shabinGravitum** [comment] 2018-08-16 16:30
Quick Fix

Add this css to the table element

display: block;
overflow: scroll;
height: 60vh;

**Comment by kracekumar** [comment] 2018-08-16 16:53
@naveenpf I was playing around to get the sense of the issue if the modified screen shared is fine, I can send a PR.

**Comment by shamonshan** [comment] 2018-08-16 17:17
Is this fixed?? In mobile view  i am able to see lot of white spaces in summary of request field

**Comment by gauthams09** [comment] 2018-08-16 17:34
I'm getting this fixed with two things:
1. Reduce content on main requests page by having link to detailed view . Vertical collapse will be added for mobile screen sizes.
2. One detailed view for each request which shows all the details of that specific request

**Closed** 2018-08-17 06:27 UTC
Labels: Working on it, high
