### ISSUE TITLE
Maps showing invalid locations outside the effected zones

### ISSUE THREAD

**Issue by dipine** [IEEEKeralaSection/rescuekerala#455] opened 2018-08-17 19:35 UTC
### Maps showing invalid locations outside the effected zones
In the live website based on the request types the information shown should be correct.

### Browser
* Chrome
* OS Type (Windows)

### Steps to reproduce
1. Go to https://keralarescue.in/map/#
2. Click on Rescue needed 
         Shows even request made for others which are not part of effected zone (ex : Bangalore)

### Expected behaviour
ex : Some people have raised "Request made for others" from Bangalore, but when we click "Rescue needed" it should show only from the zone (geofencing inside Kerala )
When some one click "Request made for others" then it is fine to show outside the zone.

### Actual behaviour
When clicked "Rescue needed" it should not show "Request made for others" which are not part of the effected zone

**Comment by bobinson** [comment] 2018-08-17 19:46
duplicate of #453 #125 etc ---> request to send a PR if possible.

**Closed** 2018-08-17 19:56 UTC
