### ISSUE TITLE
Map Geocoding Errors

### ISSUE THREAD

**Issue by josephsebk** [IEEEKeralaSection/rescuekerala#337] opened 2018-08-17 09:52 UTC
### The Geocoding on the Map seems to be wrong 
Locations shown in bangalore, USA and many other places

### Your environment
using on the map 

### Steps to reproduce
![image](https://user-images.githubusercontent.com/42460900/44260205-56504b00-a231-11e8-9c7c-e8365f70cec5.png)

### Expected behaviour
Tell us what and how exactly is it supposed to  happen

### Actual behaviour
Tell us what happens instead or what went wrong

Can fix using google geocoding with district specifc hints

**Comment by bobinson** [comment] 2018-08-17 11:09
duplicate of  #125 #225 #232 #248 #249 #252

**Closed** 2018-08-17 11:09 UTC
