### ISSUE TITLE
Donate to Chief Minister's Fund Online on the "To Contribute" page is not working

### ISSUE THREAD

**Issue by GitHub4Harish** [IEEEKeralaSection/rescuekerala#676] opened 2018-08-19 08:50 UTC
### Subject of the issue
Donate to Chief Minister's Fund Online on the "To Contribute" page is not working 

### Your environment
Chrome & IE
OS Type Windows

### Steps to reproduce
Redirects to https://donation.cmdrf.kerala.gov.in/ and gives the below error:

_Forbidden
You don't have permission to access / on this server.
Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request._

### Expected behaviour
Tell us what and how exactly is it supposed to  happen

### Actual behaviour
Tell us what happens instead or what went wrong

**Comment by saifali40** [comment] 2018-08-19 08:50
@GitHub4Harish It is working

**Comment by amiteshP** [comment] 2018-08-19 09:04
@GitHub4Harish  works fine!

**Comment by satheesht0** [comment] 2018-08-19 09:15
@GitHub4Harish unable to reproduce this issue. Probably a temporary issue at https://donation.cmdrf.kerala.gov.in/ ?

**Comment by aravindharinair** [comment] 2018-08-19 09:59
CMDRF site occasionally crashes. Solution proposed and awaiting merge at PR #614

**Comment by arish007** [comment] 2018-08-19 10:27
looks like it is down... accessing from US.
<img width="962" alt="screen shot 2018-08-19 at 3 24 56 am" src="https://user-images.githubusercontent.com/8380162/44307895-a0374f00-a35f-11e8-9f79-09d71ebbec6a.png">

**Comment by anuragkollam** [comment] 2018-08-19 10:53
https://donation.cmdrf.kerala.gov.in not working

**Comment by shiv19** [comment] 2018-08-19 10:57
seems to be working just fine here. this issue can be closed.

**Comment by anuragkollam** [comment] 2018-08-19 11:01
Now its working.

**Comment by bobinson** [comment] 2018-08-20 07:11
This is working intermittently AFIK IT mission is not running this.

**Comment by remedcu** [comment] 2018-08-20 15:48
Can close this issue as this is not related to this repo.

@syam3526 @vigneshhari @biswaz @vrthra @bobinson

**Comment by jinojossy93** [comment] 2018-08-25 18:53
Please close this issue
@biswaz @bobinson

**Closed** 2018-08-25 19:29 UTC
