### ISSUE TITLE
Text overlap on mobile in contact info/ registered requests page

### ISSUE THREAD

**Issue by gauthams09** [IEEEKeralaSection/rescuekerala#121] opened 2018-08-16 11:27 UTC
Seeing issue on mobile page due to text going outside the columns on contact info/ registered requests page. Fix is to wrap them inside the column itself

**Comment by meain** [comment] 2018-08-16 11:34
Duplicate of https://github.com/IEEEKeralaSection/rescuekerala/issues/42
Fixed with https://github.com/IEEEKeralaSection/rescuekerala/pull/93

**Comment by prajinprakash4u** [comment] 2018-08-16 11:42
```
.table-responsive>.table>tbody>tr>td, .table-responsive>.table>tbody>tr>th, .table-responsive>.table>tfoot>tr>td, .table-responsive>.table>tfoot>tr>th, .table-responsive>.table>thead>tr>td, .table-responsive>.table>thead>tr>th {
    /* white-space: nowrap; */
}
```

this will solve overlap otherwise we need to set a width for the container

**Comment by bodhish** [comment] 2018-08-16 11:47
Simple fix
In `@media screen and (max-width: 767px)`
use `white-space: normal` insted of `white-space: nowrap`

**Comment by biswaz** [comment] 2018-08-16 12:25
I fixed this manually. Please check

**Comment by gauthams09** [comment] 2018-08-16 12:26
Thanks biswas, pls close this

**Comment by naveenpf** [comment] 2018-08-16 12:29
Fixed

**Closed by naveenpf** 2018-08-16 12:29 UTC

**Comment by bobinson** [comment] 2018-08-16 12:43
Please refer to some changes requested in #132
